# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Zerocracy
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/java
assets:
  docker-password: yegor256/home#assets/docker-password
install: |
  sudo apt-get update --yes --fix-missing && sudo apt-get install --yes libxml2-utils wget curl
  curl -fsSL https://deb.nodesource.com/setup_18.x -o nodesource_setup.sh
  sudo -E bash nodesource_setup.sh
  sudo apt-get install -y nodejs npm
  rm nodesource_setup.sh
  sudo make install clean "--directory=$(pwd)"
merge:
  script: |-
    sudo docker build "$(pwd)"
    sudo make -C "$(pwd)" target/html/simple.html
release:
  pre: false
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    sed -i -e "s/0.0.0/${tag}/" entry.sh
    sed -i -e "s/0.0.0/${tag}/" Dockerfile
    sed -i -e "s/:latest/:${tag}/" action.yml
    git add entry.sh
    git add Dockerfile
    git add action.yml
    git commit -m "version set to ${tag}"
    sudo make -C "$(pwd)" target/html/simple.html
    repo=yegor256/pages-action
    sudo docker build "$(pwd)" --tag "${repo}:${tag}"
    sudo docker build "$(pwd)" --tag "${repo}:latest"
    cat ../docker-password | sudo docker login --password-stdin -u yegor256
    sudo docker push "${repo}:${tag}"
    sudo docker push "${repo}:latest"
