# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Zerocracy
# SPDX-License-Identifier: MIT
---
name: 'pages-action'
description: 'Build static pages from a Factbase'
author: 'Yegor Bugayenko <yegor256@gmail.com>'
runs:
  using: 'docker'
  image: 'docker://yegor256/pages-action:0.0.44'
inputs:
  verbose:
    description: 'Log as much debug information as possible'
    default: false
  options:
    description: 'Command line options for the "judges" tool'
    required: false
  output:
    description: 'Directory path with YAML, XML, JSON and other files generated'
    default: 'pages'
  factbase:
    description: 'Path of the factbase file'
    default: 'default.fb'
  logo:
    description: 'URL of the logo to put on the HTML page'
    default: 'https://www.zerocracy.com/svg/logo.svg'
  columns:
    description: 'Comma-separated list of columns to print in the HTML'
    default: 'when,what,who,repository,issue,details'
  hidden:
    description: 'Comma-separated list of properties to hide'
    default: '_id,_time,_version'
  today:
    description: 'ISO-8601 date-time of report generation (today, by default)'
    required: false
