# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Zerocracy
# SPDX-License-Identifier: MIT
---
name: 'pages-action'
description: 'Build static pages from a Factbase'
author: 'Yegor Bugayenko <yegor256@gmail.com>'
runs:
  using: 'docker'
  image: 'docker://yegor256/pages-action:0.7.0'
inputs:
  verbose:
    description: 'Log as much debug information as possible'
    default: false
  options:
    description: 'Command line options for the "judges" tool'
    required: false
  output:
    description: 'Directory path with YAML, XML, JSON and other files generated'
    default: 'pages'
  factbase:
    description: 'Path of the factbase file'
    required: false
  logo:
    description: 'URL of the logo to put on the HTML page'
    default: ''
  palette:
    description: 'Palette name (e.g. classic, dark, mild)'
    default: 'classic'
  adless:
    description: 'Hide all Zerocracy links, banners, and logos'
    default: false
  columns:
    description: 'Comma-separated list of columns to print in the HTML'
    default: 'when,what,repository'
  highlighted:
    description: 'Comma-separated list of columns to highlight'
    default: 'stale,tombstone'
  hidden:
    description: 'Comma-separated list of properties to hide'
    default: '_id,_time,_version'
  today:
    description: 'ISO-8601 date-time of report generation (today, by default)'
    required: false
  github-token:
    description: 'Authentication GitHub access token'
    required: false
    default: ${{ github.token }}
  timeout:
    description: 'The number of minutes to spend on each judge'
    required: false
    default: 3
  lifetime:
    description: 'The number of minutes to spend on the entire lifetime'
    required: false
    default: 5
  url:
    description: 'The URL where the static files will be visible'
    required: false
    default: ''
