name: CSS Validation

on: [push, pull_request]

jobs:
  validate-css:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Validate CSS
      uses: gchudnov/w3c-css@v1.0.0
      with:
        css: 'target/css/main.css'
        profile: 'css3'
