# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Zerocracy
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: make
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  make:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.7
          bundler-cache: true
      - run: bundle config set --global path "$(pwd)/vendor/bundle"
      - run: sudo apt-get update --yes --fix-missing && sudo apt-get install --yes libxml2-utils
      - run: make install
      - run: make
