# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Zerocracy
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: shunit2
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  shunit2:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - run: bundle config set --global path "$(pwd)/vendor/bundle"
      - run: sudo apt-get update --yes --fix-missing && sudo apt-get install --yes libxml2-utils
      - run: make install
      - run: sudo apt-get update --yes && sudo apt-get install --yes shunit2
      - run: shunit2 entry-test.sh
