# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Zerocracy
# SPDX-License-Identifier: MIT
---
# This action doesn't test the current version of the code, which is in
# the 'master' branch or in the branch that you work with. Instead, it always
# tests agains the latest version released to the Docker Hub. It's not possible,
# as far as I understand, to change this behavior.
name: test
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.7
          bundler-cache: true
      - run: bundle config set --global path "$(pwd)/vendor/bundle"
      - run: make install
      - run: |
          bundle exec judges --verbose eval test.fb " \
            f = \$fb.insert; \
            f.what = 'pmp'; \
            f.area = 'hr'; \
            f.days_of_running_balance = 28; \
            "
      # Pay attention: if this test fails, you can'f fix it in the "master"
      # branch, because it uses the "latest" version of the Docker image
      # already released to Docker Hub. In order to fix this test,
      # you should release a new version to Docker Hub and then try to fix
      # the test here. It's a two-steps process.
      - uses: ./
        with:
          verbose: true
          output: pages
          factbase: test.fb
